In [19]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn import metrics

In [3]:
df = pd.read_csv('treated_data.csv')

In [5]:
df.head()

flags                      utterance category        intent  \
0    BM           problem cancel order    ORDER  cancel_order   
1   BIM  find information cancel order    ORDER  cancel_order   
2     B         need help cancel order    ORDER  cancel_order   
3   BIP              help cancel order    ORDER  cancel_order   
4     B           problem cancel order    ORDER  cancel_order   

                                      semantic_value  semantic_value_vec_norm  
0  [ 0.9792027   1.7512335  -2.1456368  -0.207200...                34.474487  
1  [ 1.818227   -0.20782498 -1.0179275  -0.259152...                36.865709  
2  [ 3.3943768   2.520625   -4.8734274  -0.143539...                42.555865  
3  [ 1.948936    1.3805002  -4.733937    0.601046...                40.969231  
4  [ 0.9792027   1.7512335  -2.1456368  -0.207200...                34.474487

In [52]:
#Lemmas train/ test data split
X = df['utterance']
y = df['category']
X_lemma_train, X_lemma_test, y_lemma_train, y_lemma_test = train_test_split(X,y, stratify= df[['category']], test_size=0.33, random_state=42)

In [51]:
#Vector norms train/ test data split
X = df['semantic_value_vec_norm']
y = df['category']
X_norm_train, X_norm_test, y_norm_train, y_norm_test = train_test_split(X.values.reshape(-1,1),\
                                                                        y.values.reshape(-1,1),\
                                                                        stratify= df[['category']], test_size=0.33, random_state=42)

In [55]:
#Vector arrays train/test data split
X = df['semantic_value']
y = df['category']
X_vect_train, X_vect_test, y_vect_train, y_vects_test = train_test_split(X,y, stratify= df[['category']], test_size=0.33, random_state=42)

In [7]:
#TFIDF vectorizer pipeline object
tfidf_lsvc = Pipeline([('tfidf', TfidfVectorizer()),('clf', LinearSVC())])

In [49]:
#vector arrays svc
vects_lsvc = LinearSVC()

In [25]:
#Vector norm svc
norm_lsvc = LinearSVC()

In [10]:
#Fit models
tfidf_lsvc.fit(X_lemma_train, y_lemma_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', LinearSVC())])

In [56]:
vects_lsvc.fit(X_vect_train, y_vect_train)

ValueError: could not convert string to float: '[-8.2169998e-01 -1.1431099e+00 -1.6279197e-01  1.0027550e+00\n  2.8033800e+00  1.6391749e+00  4.8935854e-01  2.4603500e+00\n -4.7821999e+00  6.4871067e-01  7.3257499e+00  1.9817600e+00\n -4.7198429e+00  2.7761250e+00 -3.1727749e-01  8.7810749e-01\n  5.0738649e+00  6.4392501e-01 -2.1116025e+00 -1.2926999e-01\n -2.4107499e+00 -1.6146250e+00 -2.4929500e+00  1.1357999e+00\n -2.5620897e+00 -1.7825216e-03 -1.1287129e+00 -3.3193499e-01\n -2.0285755e-01 -1.3964874e-01  3.0693700e+00  8.1320000e-01\n -3.9172750e+00  6.3626254e-01  2.3026624e+00  7.9562747e-01\n  2.5005200e+00 -1.4224000e+00  5.1962500e+00  3.1261499e+00\n -6.3295001e-01 -3.6872494e-01 -4.7911504e-01  1.1222900e+00\n -2.1746600e+00  9.6988499e-01  6.6352496e+00 -1.7908599e+00\n -1.0367625e+00 -1.8334250e+00 -3.9679497e-01  1.5183300e+00\n -1.5384250e+00 -5.0185251e+00 -3.6138501e+00  1.1648526e+00\n -5.1686746e-01  6.3359505e-01 -1.1199981e-02  5.6995010e-01\n  5.8163252e+00  1.0048000e+00 -2.6233737e+00 -3.8313007e-01\n  3.0317502e+00  9.5727503e-01 -1.0461326e+00 -4.4929252e+00\n -2.3326998e+00  4.2725248e+00 -3.8113749e+00  1.4228749e-01\n -1.5569797e+00 -2.1191001e+00 -8.9102495e-01  3.7748001e+00\n  1.3822246e-01  1.6066601e+00 -1.3905350e+00  5.2716422e-01\n -1.6813675e+00  1.6951251e+00  1.5118575e+00  2.3059750e+00\n -2.1775877e+00 -2.7909502e-01 -1.2796999e+00 -1.5087976e+00\n  1.8662674e+00  4.5260745e-01  1.7704500e+00  2.8990400e+00\n  1.3110875e+00 -1.3404500e-01  1.6367800e+00  7.4817502e-01\n  1.0442717e+00 -1.8985450e+00 -3.4608251e-01  2.8989251e+00\n  3.5159850e+00  1.8981872e+00  1.0803500e+00 -3.0583507e-01\n -6.6687495e-01  4.8016500e+00 -2.4589226e+00 -1.6061754e+00\n -1.0650525e+00 -1.8116150e+00  6.0617626e-01 -6.6565001e-01\n -1.7270668e+00  1.5952749e+00  1.6028476e+00  3.4083500e+00\n -4.1610746e+00 -5.1047492e-01 -9.9818504e-01 -9.8593748e-01\n -3.1473000e+00 -3.1605949e+00 -1.2160375e+00  1.1905251e+00\n -4.6854499e-01 -1.5361750e+00  9.2500496e-01 -1.3498573e+00\n  3.2086751e+00 -1.9877499e-01 -2.1565874e+00  1.0239725e+00\n -1.0182331e+00 -2.4484998e-01  4.9752995e-01 -2.1118824e+00\n -1.2764378e+00 -3.0486500e+00  1.0513550e+00 -1.4562075e+00\n -1.4417000e+00  8.8594997e-01  5.8685750e-01  6.6422498e-01\n  1.3867999e+00 -1.3149992e-02 -4.8030502e-01 -2.1601751e+00\n  3.0940500e-01  2.5017400e+00 -1.6678425e+00 -1.2849987e-02\n  1.3844550e+00  4.4988245e-01  9.2224252e-01 -9.7064257e-01\n  2.7143576e+00 -1.7740998e-01 -4.8519000e-01 -2.3497851e+00\n -6.6828001e-01 -1.0400000e+00 -1.3082535e+00  5.8149749e-01\n -9.3842250e-01 -1.9977651e+00 -4.6174250e+00  5.3101498e-01\n -2.6775062e-02  9.2319500e-01 -1.9791101e+00  1.0661750e+00\n  6.4952004e-01 -1.4567001e+00  4.1283002e+00  8.1600499e-01\n -1.8233001e-01  2.7220249e+00 -8.4054744e-01 -1.7722300e+00\n  3.3949199e+00  1.3393499e+00  4.0176501e+00 -1.6294725e+00\n -2.3998278e-01 -1.8036698e+00 -2.1481149e+00 -1.8917326e+00\n  1.2912725e+00  3.8729999e+00 -2.4755199e+00 -1.4514275e-01\n -3.4888501e+00 -1.3239574e+00 -1.9627500e-01 -3.8169754e-01\n -3.0038300e+00 -1.4048851e+00  7.7994454e-01 -7.0852506e-01\n -6.0632496e+00 -2.8724250e-01 -1.0976901e+00  2.6780751e-01\n  2.1206501e+00  6.0686249e-01 -2.9637632e+00  1.7258625e+00\n  2.0125775e+00  4.1294250e-01 -1.2904050e+00 -9.5650005e-01\n  7.0932508e-02  1.5758801e+00 -1.9983598e+00  1.0388834e+00\n  1.9310625e+00 -1.1804225e+00 -4.7465760e-01  3.7630000e+00\n -2.5573063e+00  4.0353501e-01  1.6064800e+00 -2.9779646e+00\n  3.7245002e-01 -3.7177050e+00 -4.1652495e-01  2.7348499e+00\n  9.9230003e-01  1.0381250e+00  5.3352499e-01 -5.2792501e+00\n -8.0853999e-01  2.8505501e-01  9.0813249e-01  1.5303099e+00\n -2.3513751e+00 -6.1191851e-01  1.3687800e+00 -2.3753223e-01\n -3.3628998e+00 -1.6851875e+00 -1.5312750e+00  2.2144575e+00\n  9.7529757e-01 -1.4322251e-01 -1.6448799e+00 -4.1800010e-01\n  3.2307625e+00  7.5754499e-01 -1.7578751e+00 -2.9972751e+00\n -3.5619750e+00 -4.1542001e+00  1.1653750e+00 -2.2385049e+00\n  8.2141244e-01 -1.7713001e+00  5.6291002e-01  3.2085752e-01\n -4.4851251e+00  5.9996247e+00 -8.4476745e-01  8.2475495e-01\n  1.5801876e+00  5.7529569e-01 -3.8961247e-01  9.0345496e-01\n -4.2053251e+00 -1.5334924e+00 -9.6945739e-01 -4.0871200e-01\n  9.4034505e-01 -8.0332154e-01  1.5872500e+00 -4.9535999e+00\n -1.8768026e+00 -1.0439125e+00 -1.4459500e+00  2.5861051e+00\n  1.6410500e+00  6.7271250e-01  6.4953506e-01 -5.1312250e-01\n  1.2094650e+00 -1.7460126e+00  2.2389774e+00  1.6213801e+00\n -3.1972001e+00 -1.1646250e-01  1.7890126e+00 -8.9114249e-01\n  2.0454850e+00  1.7557502e-01 -1.6058912e+00  1.8609875e+00\n -1.8667492e-01 -6.0366994e-01  2.2520006e-02  4.9940103e-01]'

In [43]:
norm_lsvc.fit(X_norm_train, y_norm_train.ravel())

C:\Users\Logan\anaconda3\lib\site-packages\sklearn\svm\_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC()

In [44]:
#Predictions for test data
predictions_lemm = tfidf_lsvc.predict(X_lemma_test)
predictions_norm = norm_lsvc.predict(X_norm_test)

In [35]:
print(metrics.confusion_matrix(y_lemma_test,predictions_lemm))

[[584   0   2   0   0   0   0   0   0   0   0]
 [  1  97   0   0   0   0   0   0   0   0   0]
 [  0   0 197   0   0   0   0   0   0   0   0]
 [  0   0   0 199   0   0   0   0   0   0   0]
 [  0   0   1   0 201   0   0   0   0   0   0]
 [  0   0   0   0   0 214   0   0   0   0   0]
 [  0   0   0   0   0   0  97   0   0   0   0]
 [  1   0   0   1   0   0   0 401   0   0   0]
 [  0   0   0   1   0   0   0   0 204   0   0]
 [  1   0   0   0   0   0   0   0   0 297   0]
 [  0   0   0   1   0   0   0   0   0   0 198]]


In [36]:
print(metrics.classification_report(y_lemma_test,predictions_lemm))

                  precision    recall  f1-score   support

         ACCOUNT       0.99      1.00      1.00       586
CANCELLATION_FEE       1.00      0.99      0.99        98
         CONTACT       0.98      1.00      0.99       197
        DELIVERY       0.99      1.00      0.99       199
        FEEDBACK       1.00      1.00      1.00       202
         INVOICE       1.00      1.00      1.00       214
      NEWSLETTER       1.00      1.00      1.00        97
           ORDER       1.00      1.00      1.00       403
         PAYMENT       1.00      1.00      1.00       205
          REFUND       1.00      1.00      1.00       298
SHIPPING_ADDRESS       1.00      0.99      1.00       199

        accuracy                           1.00      2698
       macro avg       1.00      1.00      1.00      2698
    weighted avg       1.00      1.00      1.00      2698



In [47]:
print(metrics.confusion_matrix(y_norm_test,predictions_norm))

[[  0   0   0 586   0   0   0   0   0   0   0]
 [  0   0   0  97   0   0   1   0   0   0   0]
 [  0   0   0 196   0   0   1   0   0   0   0]
 [  0   0   0 199   0   0   0   0   0   0   0]
 [  0   0   0 202   0   0   0   0   0   0   0]
 [  0   0   0 214   0   0   0   0   0   0   0]
 [  0   0   0  96   0   0   1   0   0   0   0]
 [  0   0   0 403   0   0   0   0   0   0   0]
 [  0   0   0 205   0   0   0   0   0   0   0]
 [  0   0   0 298   0   0   0   0   0   0   0]
 [  0   0   0 199   0   0   0   0   0   0   0]]


In [46]:
print(metrics.classification_report(y_norm_test,predictions_norm))

                  precision    recall  f1-score   support

         ACCOUNT       0.00      0.00      0.00       586
CANCELLATION_FEE       0.00      0.00      0.00        98
         CONTACT       0.00      0.00      0.00       197
        DELIVERY       0.07      1.00      0.14       199
        FEEDBACK       0.00      0.00      0.00       202
         INVOICE       0.00      0.00      0.00       214
      NEWSLETTER       0.33      0.01      0.02        97
           ORDER       0.00      0.00      0.00       403
         PAYMENT       0.00      0.00      0.00       205
          REFUND       0.00      0.00      0.00       298
SHIPPING_ADDRESS       0.00      0.00      0.00       199

        accuracy                           0.07      2698
       macro avg       0.04      0.09      0.01      2698
    weighted avg       0.02      0.07      0.01      2698



C:\Users\Logan\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Logan\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Logan\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
